### ISSUE TITLE
Some question about LabelConvert training

### ISSUE THREAD

**Issue by yy9568** [naver-ai/ZIM#13]
1. The paper mentioned that it referred to mask-guided matting works to build the mask-to-matting model. Then, during the training process, will the mask be processed into a trimap? Or is it to build a learning paradigm of **img + mask -> matting**?
2. **Selective Transformation Learning** is quite easy to understand. However, for **Spatial Generalization Augmentation**, my question is that when you use the **random cut-out technique** and cut out the mask and matting, will the corresponding image adopt the same cut-out method?

<img width="328" alt="Snipaste_2024-12-25_19-06-49" src="https://github.com/user-attachments/assets/57660b51-f9a3-473d-87cb-ff921f753d70" />

**Comment by qjadud1994** [comment]
Hi.

1. The converter model is trained with the `img + mask -> matting` learning paradigm.
2. The figure correctly illustrates the pipeline of Spatial Generalization Augmentation: During training the converter model, both the segmentation label and the corresponding matte label are randomly cropped in the same regions (without applying it to the input image). The purpose of it is described in our paper: `By exposing the converter to irregular and incomplete input patterns, this augmentation forces the converter to adapt to diverse spatial structures and unseen patterns, thus enhancing its generalization capability`.
