### ISSUE TITLE
Improve Hugging Face integration

### ISSUE THREAD

**Issue by NielsRogge** [naver-ai/ZIM#4]
Hi @beomyoung-kim!

Congrats on your work, I discovered it on Twitter.

I'm Niels from the open-source team at Hugging Face, and got some tiny suggestions regarding improving the integration of ZIM on Hugging Face, namely:

- would be great to push the models to a dedicated model repo, rather than hosting the weights inside the Space. Refer to https://huggingface.co/docs/huggingface_hub/en/guides/upload for a guide.
- would be great to link the models and Space to the paper page, which I indexed here: https://huggingface.co/papers/2411.00626. As can be seen on the right, no "models", "datasets", or "spaces" are linked yet, you can link them by adding the paper page URL in the respective READMEs.
- perhaps it would make sense to push everything to https://huggingface.co/naver-ai, rather than https://huggingface.co/naver-iv (to be consistent with Github?).

Let me know if you need any help!

Cheers,

Niels

**Comment by qjadud1994** [comment]
@NielsRogge 

We appreciate the detailed instructions.

We updated the models ([vitb](https://huggingface.co/naver-iv/zim-anything-vitb), [vitl](https://huggingface.co/naver-iv/zim-anything-vitl)) and linked the [paper](https://huggingface.co/papers/2411.00626) to models, datasets, and spaces.

If you have any other suggestions, please let me know.

Best,

Beom

**Comment by NielsRogge** [comment]
That's awesome :) https://huggingface.co/papers/2411.00626 looks great now. 

Some further suggestions:
- the checkpoints could be removed from the Space: https://huggingface.co/spaces/naver-iv/ZIM_demo_with_SAM/tree/main/ckpts. Rather, it's advised to use the following inside the Space:
```python
from huggingface_hub import hf_hub_download

filepath = hf_hub_download(repo_id="naver-iv/zim-anything-vitb", filename="ckpts/zim_vit_b_2043/encoder.onnx")
```
One could leverage this method to also automatically download checkpoints from the hub inside the Github repo, rather than requiring users to perform a manual download. This is also what the from_pretrained methods in HF libraries use behind the scenes. See here for docs: https://huggingface.co/docs/huggingface_hub/en/guides/download.
- we could enable download stats for your models. See [https://huggingface.co/docs/hub/models-download-stats on how to enable them. See https://github.com/huggingface/huggingface.js/pull/900 as an example.

**Comment by qjadud1994** [comment]
@NielsRogge

We appreciate the additional suggestions.

We removed the checkpoints and updated the space using `hf_hub_download`.
Also, we created the `collection` (https://huggingface.co/collections/naver-iv/zim-6739a32211b7efeeed83b674).

Please let me know if you have any more suggestions, or close the issue if not.

Sincerely.

Beom

**Comment by NielsRogge** [comment]
Awesome, thanks a lot :) let me know if you have any exciting future releases! Happy to amplify.

I you want to share about ZIM on social media, let us know, we can also help you amplify.

**Comment by qjadud1994** [comment]
@NielsRogge 

Thanks.
We would greatly appreciate it if you could share our work on social media :)

**Comment by NielsRogge** [comment]
Actually @qjadud1994 I have some more suggestions!

The Space seems to run on CPU now, but you can leverage ZeroGPU (which shares underlying A100 GPUs among hundreds of Spaces): https://huggingface.co/zero-gpu-explorers. The GPU only gets loaded when a user submits something to the Space.

See this demo which is very similar to yours: https://huggingface.co/spaces/briaai/BRIA-RMBG-2.0
