### ISSUE TITLE
About the inference time

### ISSUE THREAD

**Issue by rentainhe** [naver-ai/ZIM#7]
Hi authors, when running the ZiM-L model, we met such a problem here:

![image](https://github.com/user-attachments/assets/95eede92-a6c7-48cf-b2fe-df0d66c98413)

And the inference speed is very slow, is there any solution about this issue.

**Comment by qjadud1994** [comment]
The environment settings are incorrectly installed if the inference speed exceeds 5 seconds.
Check the installation docs below.

> To enable GPU acceleration, please install the compatible onnxruntime-gpu package based on your environment settings (CUDA and CuDNN versions), following the instructions in the [onnxruntime installation docs](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements).

**Comment by rentainhe** [comment]
> The environment settings are incorrectly installed if the inference speed exceeds 5 seconds. Check the installation docs below.
> 
> If the environment settings are correctly installed, there will be no red-colored error: `error: libsublasLt.so.11: cannot open shared object file: No such file or directory` (you may see only the yellow warning messages).
> 
> > To enable GPU acceleration, please install the compatible onnxruntime-gpu package based on your environment settings (CUDA and CuDNN versions), following the instructions in the [onnxruntime installation docs](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements).

Thanks a lot for you reply, I have already fixed this issue and run correctly on CUDA device

**Comment by AsuradaYuci** [comment]
@rentainhe how to fix this issue, Could you provide some details?
