### ISSUE TITLE
About training cost

### ISSUE THREAD

**Issue by Nuyoah13** [naver-ai/ZIM#8]
As mentioned in your paper, you fine-tuned the ZIM model on 1% of the SA1B- Matte dataset. I wonder the training cost of the fine-tuning process, i.e., how many cards(v100?) and how long did you train for 500K iterations. Thanks.

**Comment by qjadud1994** [comment]
We used 8 V100 GPUs and training (finetuning) was completed within 7 days.

**Comment by Nuyoah13** [comment]
> We used 8 V100 GPUs and training (finetuning) was completed within 7 days.

thanks a lot.
